# Generated by Django 3.0.5 on 2020-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200430_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='published_at',
            field=models.DateField(),
        ),
    ]
