# Generated by Django 3.0.5 on 2020-05-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200430_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
